### ISSUE TITLE
Is there a version for hg38 genome?

### ISSUE THREAD

**Issue by santataRU** [jlbuerer/LaMIRA#8]
Dear developer,

Is there a version for the hg38 genome?

Thanks,
Xiao

**Comment by jlbuerer** [comment]
The software functions independent of any particular genome or annotation. You simply need to provide the bowtie index and GTF annotation file for the genome you would like to use for mapping.

**Comment by santataRU** [comment]
Hi, Jlbuerer,

Thank you very much for your help!

The input fastq requires uniform length and it is suggested that reads are trimmed to uniform length in the adaptor trimming step, what adaptor trimming tool you used, and what arguments you used in the command line to trim reads to uniform length?

Regards,

Xiao

**Comment by jlbuerer** [comment]
I use [fastp](github.com/OpenGene/fastp) for adapter trimming
